name: Build Application and Make Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build-type: Release
      environment: Release
    secrets: inherit

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "true"
          path: "PrismLauncher-source"
      - name: Download artifacts
        uses: actions/download-artifact@v7
      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Render release notes
        run: |
          sed "s/{{VERSION}}/${{ env.VERSION }}/g" PrismLauncher-source/.github/release-template.md > RELEASE_BODY.md
      - name: Package artifacts properly
        run: |
          for d in PrismLauncher-Windows-MSVC*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            NAME="PrismLauncher-Windows-MSVC"
            test -z "${INST}" || mv PrismLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            cd ..
          done

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: PrismLauncher Fork ${{ env.VERSION }} (Windows)
          draft: true
          prerelease: false
          body_path: RELEASE_BODY.md
          fail_on_unmatched_files: true
          files: |
            PrismLauncher-Windows-MSVC-Setup-${{ env.VERSION }}.exe
